name: dopamine-env
channels:
  - defaults
dependencies:
  - ca-certificates=2019.1.23
  - certifi=2018.11.29
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libstdcxx-ng=8.2.0
  - ncurses=6.1
  - openssl=1.1.1b
  - pip=19.0.3
  - python=3.6.8
  - readline=7.0
  - setuptools=40.8.0
  - sqlite=3.26.0
  - tk=8.6.8
  - wheel=0.33.1
  - xz=5.2.4
  - zlib=1.2.11
  - pip:
    - absl-py==0.7.0
    - aicrowd-repo2docker==0.7.0
    - astor==0.7.1
    - atari-py==0.1.7
    - atomicwrites==1.3.0
    - attrs==19.1.0
    - chardet==3.0.4
    - decorator==4.3.2
    - docker==3.7.0
    - docker-pycreds==0.4.0
    - dopamine-rl==2.0.1
    - enum34==1.1.6
    - escapism==1.0.0
    - future==0.17.1
    - gast==0.2.2
    - gin-config==0.1.4
    - grpcio==1.11.1
    - gym==0.12.0
    - h5py==2.9.0
    - idna==2.8
    - ipython-genutils==0.2.0
    - jinja2==2.10
    - keras-applications==1.0.7
    - keras-preprocessing==1.0.9
    - markdown==3.0.1
    - markupsafe==1.1.1
    - mlagents-envs==0.6.2
    - mock==2.0.0
    - more-itertools==6.0.0
    - numpy==1.16.1
    - -e git+https://github.com/Unity-Technologies/obstacle-tower-env.git@f3c6ec45c7b9a2e928541d48e32243edc5bc5bb8#egg=obstacle_tower_env
    - opencv-python==4.0.0.21
    - pbr==5.1.3
    - pillow==5.4.1
    - pluggy==0.9.0
    - protobuf==3.6.1
    - py==1.8.0
    - pyglet==1.3.2
    - pytest==3.10.1
    - python-json-logger==0.1.10
    - requests==2.21.0
    - ruamel.yaml==0.15.89
    - scipy==1.2.1
    - six==1.12.0
    - tensorboard==1.12.2
    - tensorflow-gpu==1.12.0
    - termcolor==1.1.0
    - traitlets==4.3.2
    - urllib3==1.24.1
    - websocket-client==0.55.0
    - werkzeug==0.14.1

